DTA_FOLDER: "dta"
MDL_FOLDER: "dta/models"
RAW_DTA_FOLDER: "dta/raw-dta"
IMG_FOLDER: "img"
TXT_FOLDER: "txt"
SRC_FOLDER: "src"
ANSIBLE_INVENTORY: "ansible/inventory"
ANSIBLE_LOCALHOST: "ansible/localhost"
FOLDS: 5
REPEATS: 5
