DTA_FOLDER: "dta"
MDL_FOLDER: "dta/models"
RAW_DTA_FOLDER: "dta/raw-dta"
IMG_FOLDER: "img"
TXT_FOLDER: "txt"
SRC_FOLDER: "src"
FOLDS: 5
REPEATS: 5


COLORS:
  #PP:
  p1:
    - "#055073"
    - "#0BB2FF"
  #ERC:
  p3:
    - "#B77F22"
    - "#FFB232"
  #PSC:
  p4:
    - "#A72B29"
    - "#E73B39"
  #Ciutadans:
  p6:
    - "#A94A0D"
    - "#EB6109"
  #CUP:
  p10:
    - "#BBAE00"
    - "#FFED00"
  #En Comú Podem:
  p18:
    - "#340F34"
    - "#6E236E"
  #Junts per Catalunya:
  p21:
    - "#00857A"
    - "#00C3B2"
  #VOX:
  p23:
    - "#3D7416"
    - "#63BE21"
  #Sumar:
  p24:
    - "#8A0E34"
    - "#e61857"
  #Altres
  p80:
    - "#AEAEAE"
    - "#AEAEAE"
  #BAI
  p9000:
    - "#AEAEAE"
    - "#AEAEAE"


PRETTY_PARTY_NAMES:
  "p1": "PP"
  "p3": "ERC"
  "p4": "PSC"
  "p6": "Ciudadanos"
  "p10": "CUP"
  "p18": "ECP"
  "p21": "Junts"
  "p23": "VOX"
  "p24": "Sumar-ECP"
  "p80": "Altres"
  "p9000": "BAI"

