DTA_FOLDER: "dta"
MDL_FOLDER: "dta/models"
RAW_DTA_FOLDER: "dta/raw-dta"
IMG_FOLDER: "img"
TXT_FOLDER: "txt"
SRC_FOLDER: "src"
FOLDS: 5
REPEATS: 5
COLORS:
  PSC:
    - "#A72B29"
    - "#E73B39"
  ERC:
    - "#B77F22"
    - "#FFB232"
  Junts:
    - "#00857A"
    - "#00C3B2"
  PP:
    - "#055073"
    - "#0BB2FF"
  CUP:
    - "#BBAE00"
    - "#FFED00"
  Vox:
    - "#3D7416"
    - "#63BE21"
  ECP:
    - "#340F34"
    - "#6E236E"
  Cs:
    - "#A94A0D"
    - "#EB6109"
PRETTY_PARTY_NAMES:
  "PSCPSOE": "PSC"
  "ERC": "ERC"
  "Cs": "Cs"
  "CUP": "CUP"
  "En.Comu.Podem": "ECP"
  "Junts.per.Catalunya": "Junts"
  "PP": "PP"
  "Vox": "Vox"
