- hosts: all
  tasks:    
    - name: Clone the repository
      git:
        repo: git@github.com:griverorz/ceo-barometer-src.git
        version: main
        dest: /opt/ceobarometer
      become: no

    - name: Add keyserver for R
      become: true
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E298A3A825C0D65DFD57CBB651716619E084DAB9

    - name: Add repository for R
      apt_repository:
        repo: deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/
        state: present
        update_cache: True
       
    - name: Install system dependencies
      become: true
      apt:
        name: ['gcc', 'emacs', 'libomp-dev', 'r-base', 'python3', 'python3-pip']
        state: latest

    - name: Install Snakemake
      pip:
        name:
          - Snakemake
          
    - name: Copy Rprofile, Renviron and data files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'Rprofile', dest: '$HOME/.Rprofile' }
        - { src: 'Renviron', dest: '$HOME/.Renviron' }
        - { src: '../dta/raw-dta/', dest: '/opt/ceobarometer/dta/raw-dta/' }
      
    - name: Set R library
      file:
        path: /opt/R
        state: directory
        mode: 0777
        owner: root
      
    - name: Install R packages
      shell: Rscript -e "install.packages(\"{{ item }}\")"
      with_items:
        - haven
        - yaml
        - survey
        - labelled
        - caret
        - dplyr
        - xgboost
        - stringi
        - pROC
        - MLmetrics
